### ISSUE TITLE
관리자페이지(자소서관리) - url 및 response 변경사항

### ISSUE THREAD

**Issue by aaajinnn** [RAGbasedResumeEditor/resumeEditorBackend#100]
1. 자소서 목록
**변경사항** : /list 제거
-수정 전 : /admin/resume/board/list
-수정 후 : /admin/resume/board
response
```
{
    "total_page": 10,
    "resume_board_list": [
        {
            "rating": 0.0,
            "rating_count": 0,
            "read_num": 2,
            "title": " ",
            "w_date": "2024-07-10T12:15:27.000+00:00",
            "username": " ",
            "rnum": 341
        },
        ...
}
```
2. 자소서 검색
**변경사항** : group 제거, /list제거, 제목/별점으로 검색 분리(pageNo 디폴트 0)
* 제목으로 자소서 검색
-수정전 : /admin/resume/board/list/search?group=title
-수정후 : /admin/resume/board/search/title?title=""
* 별점으로 자소서 검색 (raiting 디폴트 3)
-수정전 : /admin/resume/board/list/search?group=rating
-수정후 : /admin/resume/board/search/rating?rating=

**Comment by MinjoonHK** [comment]
해결했습니다~
