### ISSUE TITLE
관리자 페이지(회원 관리) - url 및 request/response 변경사항

### ISSUE THREAD

**Issue by ibnuena** [RAGbasedResumeEditor/resumeEditorBackend#101]
1. 회원 관리
* 회원 검색
   - 수정 전 : /admin/user/search?page={value}&group={value}&keyword={value}
   - 수정 후 : /admin/user/list/search

```
{
	"page":int,
	"group":"string", //username, email, company, occupation, wish
	"keyword":"string"
}
```
-> request : parameter에서 reqeust body로 변경
    
```
{
    "total_page": 10,
    "user_list": [
        {
            "rating": 0.0,
            "rating_count": 0,
            "read_num": 2,
            "title": " ",
            "w_date": "2024-07-10T12:15:27.000+00:00",
            "username": " ",
            "rnum": 341
        },
        ...
} 
```
-> response 

* 회원 목록 : /admin/user/list
```
{
    "total_page": 10,
    "user_list": [
        {
            "rating": 0.0,
            "rating_count": 0,
            "read_num": 2,
            "title": " ",
            "w_date": "2024-07-10T12:15:27.000+00:00",
            "username": " ",
            "rnum": 341
        },
        ...
} 
```
-> response

**Comment by MinjoonHK** [comment]
해결했습니다.

**Comment by MinjoonHK** [comment]
해결했습니다~

let res = axiosInstance
      .get("/admin/user/list/search", {
        params: {
          pageNo: page,
          keyword: search,
          group: searchOption,
        },
      })
      .then((res) => {
        let newData = res.data.user_list.map((data: any, idx: number) => {
          return {
            ...data,
            key: idx,
            inDate: data.inDate.slice(0, 10),
            delDate: data.delDate ? data.delDate.slice(0, 10) : null,
          };
        });
        setUserList(newData);
        setTotalPage(res.data.total_page);
      })
