### ISSUE TITLE
마이 페이지 - 매핑 어노테이션 및 url 변경사항

### ISSUE THREAD

**Issue by aaajinnn** [RAGbasedResumeEditor/resumeEditorBackend#98]
구글 드라이브 문서에 작성하였던 변경사항을 issue를 통해 다시한번 공유합니다.

1. 회원탈퇴
 **변경사항** : @PostMapping에서 @DeleteMapping 으로 수정, /delete가 직접적으로 언급되지 않도록 수정
-수정 전 : @PostMapping("/user/delete")
     /user/delete
-수정 후 : @DeleteMapping("/user/{uNum}")
     /user/{uNum}
2. 회원정보 수정
 **변경사항** : @PostMapping 에서 @PatchMapping로 수정, /update가 직접적으로 언급되지 않도록 수정
-수정 전 : @PostMapping("/user/update")
     /user/update
-수정 후 : @PatchMapping("/user")
     /user

**Comment by MinjoonHK** [comment]
해결했습니다!
