### ISSUE TITLE
랜딩페이지 - url 및 response 변경사항

### ISSUE THREAD

**Issue by aaajinnn** [RAGbasedResumeEditor/resumeEditorBackend#99]
구글 드라이브 문서에 작성하였던 변경사항을 issue를 통해 다시한번 공유합니다.

총 회원수, 총 방문자 수, 총 첨삭 수, 총 게시글 수의 response는 수정된 회원/자소서 통계 페이지의 response와 동일합니다.
**변경사항** : group제거 후 분리

* 총 회원수
수정전 : /landing/statistics?group=countUser
수정후 : /landing/statistics/user-count
```
{
    "total_count": 70
}
```
* 총 방문자 수
수정전 : /landing/statistics?group=visitTotal
수정후 : /landing/statistics/total-visit
```
{
    "visit_total": 1160
}
```
* 총 첨삭 수
수정전 : /landing/statistics?group=editTotal
수정후 : /landing/statistics/total-edit
```
{
    "total_edit": 332
}
```
* 총 게시글 수
수정전 : /landing/statistics?group=boardTotal
수정후 : /landing/statistics/total-board 
```
{
    "total_board": 93
}
```
* 랜딩페이지 리뷰(아직 프론트에서 사용하고있지 않지만 적어놓겠습니다.)
/landing/review
```
{
    "reviews": [
        {
            "content": "자소서 첨삭 서비스 덕분에 취업에 성공했습니다!",
            "rating": 5
        },
        {
            "content": "reditor의 꼼꼼한 첨삭으로 자소서가 완벽해졌어요.",
            "rating": 5
        },
        ...
    ]
}
```

**Comment by MinjoonHK** [comment]
해결했습니다~

 const fetchLandingStatData = async (group: string) => {
    let res = await axios.get(`/landing/statistics/${group}`).then((res) => {
      switch (group) {
        case "user-count":
          setTotalUser(res.data.total_count);
          break;
        case "total-visit":
          setTotalVisitor(res.data.visit_total);
          break;
        case "total-edit":
          setTotalEdit(res.data.total_edit);
          break;
        case "total-board":
          setTotalResume(res.data.total_board);
          break;
      }
    });
  };

  useEffect(() => {
    Promise.all([
      fetchLandingStatData("user-count"),
      fetchLandingStatData("total-visit"),
      fetchLandingStatData("total-edit"),
      fetchLandingStatData("total-board"),
    ]);
  }, []);
